### ISSUE TITLE
images at top of example page are broken

### ISSUE THREAD

**Issue by marco-m** [quil/quil-examples#14]
looks like image links on the first half of

https://github.com/quil/quil-examples/blob/master/src/quil_sketches/gen_art/README.md

are broken.

**Comment by nbeloglazov** [comment]
Yes, they are broken. Do you know good place to host images to be included in README?

**Comment by marco-m** [comment]
Good question :-)

In my opinion, the safest and guaranteed to work forever is to add them to this git repo. I used to think this was not clean. But it works and will never break.

If you are against that, then I am very happy with https://www.netlify.com/, they have a free plan that you could use. Putting the images there is as simple as doing `netlify deploy` in the images directory.

**Comment by DahnJ** [comment]
@nbeloglazov how did you fix the second half of the images in https://github.com/quil/quil-examples/commit/b038a063806167c05c40e71a1297356cfbad521a#diff-33731b788a1e33572fbcd950710feee37b9e05467e9b783c8a0817d4ac1f1e2c ?

If that option isn't available anymore, then I'd happily submit a PR using e.g [this method](https://medium.com/@justynagolawska/how-to-easily-add-screenshots-into-your-readme-file-on-github-d806a01d6ffd) or some external hosting.

**Comment by nbeloglazov** [comment]
I don't remember. It was 7 years ago :(

чц, 23 вер 2021, 08:43 карыстальнік Dahn ***@***.***> напісаў:

**Comment by DahnJ** [comment]
No problem, I provided a possible solution in https://github.com/quil/quil-examples/pull/17

I chose to include the images in the repo, it seemed to be the most robust option to me.
